version: '3'  #docker version
services:
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html" #sync project dir with container web dir 
    ports:
      - "8080:80" #expose port for local access to the app in browser
      - 443:443 #expose ssl port for nginx proxy (if needed)
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password #set your own password here
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 #allow empty password, if you want
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
      - "8001:80"
      environment:
       - PMA_HOST =db 
       - PMA_PORT=3306